@baseUrl = http://localhost:5080/api/v1
@csrfToken = o6HoSQDY2BNLTIqVi9vXBTA9n1EDX3bELfm8u6djmamJcki/xUFXDIhEHCx6o2sWSGMIvYVnF8UoRp6KPh0jiw==

# @name create_user

POST {{baseUrl}}/users/signup
Content-Type: application/json

{
  "username":"gabrielsantos123",
  "password": "123456789",
  "email":"gabriel@outlook.com",
  "bio":"gosto de codar"
}

###

# @name login_user_with_csrf

POST {{baseUrl}}/users/login
Content-Type: application/json
#X-CSRF-Token: qxRvpDML+LOUMKXllUegUMzitTOSQH6WQyYixrdhumwE62OyndLauJLje3mnKgMX8CvuBFmYGCuntoVik6Br6A==

{
  "email": "gabriel@outlook.com",
  "password": "123456789"
}

###

# @name logout_user

POST {{baseUrl}}/users/logout
Content-Type: application/json
X-CSRF-Token: qxRvpDML+LOUMKXllUegUMzitTOSQH6WQyYixrdhumwE62OyndLauJLje3mnKgMX8CvuBFmYGCuntoVik6Br6A==

{
  "email":"gabriel@outlook.com",
  "password": "123456789"
}


###

# @name get_csrf_token

# Obter o Token CSRF
GET {{baseUrl}}/csrf-token
Content-Type: application/json


###

# @name create_product

POST {{baseUrl}}/products/
Content-Type: application/json

{
  "product_name": "Camisa do Flamengo",
  "description": "Descrição do produto 1",
  "price": 100.00,
  "auction_end": "2024-12-31T23:59:59Z"
}


